name = "kolaytara"
compatibility_date = "2025-10-28"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "kolaytara-users"
database_id = "d0e5a753-7e3b-42c5-93df-78aad83502cf"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "kolaytara-uploads"
